/*
 * PriceChangeDialog.java
 *
 * Created on __DATE__, __TIME__
 */

package com.sxt.view.xsgl_view;

import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.Vector;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.event.AncestorEvent;
import javax.swing.event.AncestorListener;

import com.sxt.dao.factory.DaoFactory;


/**
 * 
 * @author __USER__
 */
public class SellAdd extends javax.swing.JDialog implements
		ItemListener {
	private Vector<Vector> data;
	private Vector<String> name;

	/** Creates new form PriceChangeDialog */
	public SellAdd() {
		setModal(true);
		setPreferredSize(new Dimension(600, 350));
		initComponents();
		setLocationRelativeTo(null);
		setVisible(true);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {
		this.setLayout(null);
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jComboBox1 = new javax.swing.JComboBox();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jLabel15 = new javax.swing.JLabel();
		jLabel16 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();
		jLabel11 = new javax.swing.JLabel();
		jLabel12 = new javax.swing.JLabel();
		jLabel13 = new javax.swing.JLabel();
		jLabel14 = new javax.swing.JLabel();
		jLabel17 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jTextField1=new JTextField();
		

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		jLabel1.setText("商品名称");

		jLabel2.setText("产地");
		jLabel6.setText("jLabel6");

		jLabel3.setText("包装");
		jLabel7.setText("jLabel7");

		jLabel4.setText("单价");
		jLabel15.setText(" sdads");

		jComboBox1.setModel(new DefaultComboBoxModel());

		jLabel8.setText("规格");
		jLabel12.setText("jLabel12");

		jLabel9.setText("简称");
		jLabel13.setText("无");

		jLabel10.setText("单位");
		jLabel14.setText("jLabel14");

		jLabel11.setText("数量");

		jTextField1.setText("");

		jButton1.setText("确定");
		jButton1.setCursor(new Cursor(Cursor.HAND_CURSOR));

		jButton1.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub
				inputnum = jTextField1.getText();
				
				dispose();
			}
		});

		jButton2.setText("关闭");
		jButton2.setCursor(new Cursor(Cursor.HAND_CURSOR));
		jButton2.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub
				dispose();
			}
		});
		jLabel1.setBounds(30, 30, 60, 30);
		jLabel6.setBounds(100, 70, 60, 30);
		jLabel7.setBounds(100, 110, 60, 30);
		jLabel9.setBounds(360, 70, 60, 30);
		jLabel10.setBounds(360, 110, 60, 30);
		jLabel11.setBounds(360, 150, 60, 30);
		jLabel13.setBounds(460, 70, 60, 30);
		jLabel14.setBounds(460, 110, 60, 30);
		jTextField1.setBounds(430, 150, 60, 30);
		jLabel15.setBounds(100, 150, 60, 30);
		jLabel16.setBounds(100, 190, 60, 30);
		jComboBox1.setBounds(100, 35, 200, 25);
		jLabel8.setBounds(360, 30, 60, 30);
		jLabel12.setBounds(460, 30, 60, 30);
		jLabel2.setBounds(30, 70, 60, 30);
		jLabel3.setBounds(30, 110, 60, 30);
		jLabel4.setBounds(30, 150, 60, 30);
		jButton1.setBounds(150, 260, 80, 30);
		jButton2.setBounds(350, 260, 80, 30);

		name = new Vector<String>();
		data = DaoFactory.getSpDao().spInquiry();
		for (int i = 0; i < data.size(); i++) {
			String dbname = data.get(i).get(0).toString();
			name.add(dbname);
		}
		DefaultComboBoxModel dcbm = new DefaultComboBoxModel(name);
		jComboBox1.setModel(dcbm);

		// 下拉框加载时给此会话填充数据
		jComboBox1.addAncestorListener(new AncestorListener() {
			@Override
			public void ancestorRemoved(AncestorEvent event) {
			}

			public void ancestorMoved(AncestorEvent event) {
			}

			public void ancestorAdded(AncestorEvent event) {
				setLableText(data, 0);
			}
		});

		this.add(jLabel15);
		this.add(jTextField1);
		this.add(jLabel6);
		this.add(jLabel7);
		this.add(jLabel8);
		this.add(jLabel9);
		this.add(jLabel10);
		this.add(jLabel11);
		this.add(jLabel12);
		this.add(jLabel13);
		this.add(jLabel14);
		this.add(jLabel2);
		this.add(jLabel3);
		this.add(jLabel4);
		this.add(jLabel8);
		this.add(jComboBox1);
		this.add(jLabel1);
		this.add(jButton1);
		this.add(jButton2);
		jComboBox1.addItemListener(this);

		pack();
	}// </editor-fold>
		// GEN-END:initComponents

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				SellAdd dialog = new SellAdd();
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
			}
		});
	}
    public  Vector getvector(){
    	if(inputnum==null){
    		inputnum=Integer.toString(0);
    	}
		for (int i = 0; i < data.size(); i++) {
			if(data.get(i).get(0).equals(jComboBox1.getSelectedItem())){
				data.get(i).add(inputnum);
				Vector myvector=data.get(i);
				return myvector;
			}
		}
    	
    	return null;	
    }
	public void setLableText(Vector<Vector> data, int i) {

		jLabel6.setText(data.get(i).get(1).toString());

		jLabel7.setText(data.get(i).get(4).toString());

		jLabel15.setText(data.get(i).get(5).toString());

		jLabel12.setText(data.get(i).get(3).toString());

		jLabel14.setText(data.get(i).get(2).toString());

	}

	// GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JComboBox jComboBox1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JLabel jLabel15;
	private javax.swing.JLabel jLabel16;
	private javax.swing.JLabel jLabel17;
	private JTextField jTextField1;
	private String inputnum;

	// End of variables declaration//GEN-END:variables

	// 下拉框选择时填充会话内容的事件
	@Override
	public void itemStateChanged(ItemEvent e) {
		// TODO Auto-generated method stub
		if (e.getStateChange() == ItemEvent.SELECTED) {
			// TODO Auto-generated method stub
			int num = name.size();
			for (int i = 0; i < num; i++) {
				if (e.getItem().toString().equals(name.get(i)))
					setLableText(data, i);
		}

		}

	}

}