/*
 * PriceChangeDialog.java
 *
 * Created on __DATE__, __TIME__
 */

package com.sxt.view.kcgl_view;

import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.Properties;
import java.util.Vector;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.event.AncestorEvent;
import javax.swing.event.AncestorListener;

/**
 * 
 * @author __USER__
 */
public class KcAlertDialog extends javax.swing.JDialog {
	/** Creates new form PriceChangeDialog */
	private Vector vector;
	private static Properties pro = new Properties();
	private static File propertyFile = new File(
			"F:\\ECLIPSE\\Sell1.0\\config\\alertvalue.properties");
	static {
		InputStream in = null;
		try {
			in = new FileInputStream(propertyFile);
			pro.load(in);
		} catch (FileNotFoundException e2) {
			// TODO Auto-generated catch block
			e2.printStackTrace();
		} catch (IOException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		} finally {
			try {
				in.close();
			} catch (IOException e3) {
				// TODO Auto-generated catch block
				e3.printStackTrace();
			}
		}
	}

	public KcAlertDialog(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		setPreferredSize(new Dimension(600, 350));
		initComponents();
		setLocationRelativeTo(null);
		setVisible(true);
	}
	//库存预警界面构造方法
	public KcAlertDialog(final Vector vector) {
		super(new Frame(), true);
		this.vector = vector;
		//调用初始化方法
		initComponents();
		jLabel6.setText(vector.get(4).toString());
		jLabel11.setText(vector.get(5).toString());
		jLabel12.setText(vector.get(1).toString());
		jLabel16.setText(vector.get(0).toString());
		jLabel13.setText(vector.get(3).toString());
		jLabel14.setText(vector.get(6).toString());
		jLabel7.setText(vector.get(2).toString());
		jTextField1.setText(vector.get(7).toString());
		jTextField2.setText(vector.get(8).toString());
		setSize(new Dimension(600, 350));
		setResizable(false);
		setLocationRelativeTo(null);
		setVisible(true);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {
		this.setLayout(null);
		jLabel1 = new JLabel();
		jLabel2 = new JLabel();
		jLabel3 = new JLabel();
		jLabel4 = new JLabel();
		jLabel5 = new JLabel();
		jLabel6 = new JLabel();
		jLabel7 = new JLabel();
		jLabel11 = new JLabel();
		jTextField2 = new JTextField();
		jLabel8 = new JLabel();
		jLabel9 = new JLabel();
		jLabel10 = new JLabel();
		jLabel11 = new JLabel();
		jLabel12 = new JLabel();
		jLabel13 = new JLabel();
		jLabel14 = new JLabel();
		jLabel15 = new JLabel();
		jLabel16 = new JLabel();
		jTextField1 = new JTextField();
		jButton1 = new JButton("确定");
		jButton1.setFont(new Font("楷体", 13, 15));
		jButton2 = new JButton("关闭");
		jButton2.setFont(new Font("楷体", 13, 15));

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		jLabel1.setText("商品编号");

		jLabel16.setText("16");

		jLabel2.setText("规格");

		jLabel3.setText("产地");

		jLabel4.setText("包装类型");

		jLabel5.setText("设置库存预警值");

		jLabel6.setText("6");

		jLabel7.setText("7");

		jLabel11.setText("11");

		jTextField2.setText("f2");

		jLabel8.setText("商品名称");

		jLabel9.setText("单位");

		jLabel10.setText("单价");

		jLabel12.setText("12");

		jLabel13.setText("13");

		jLabel14.setText("14");

		jLabel15.setText("当前库存");

		jTextField1.setText("f1");

		jButton1.setCursor(new Cursor(Cursor.HAND_CURSOR));
		jButton1.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub
				pro.setProperty(vector.get(0).toString(), jTextField2.getText());
				OutputStream out = null;
				try {
					out = new FileOutputStream(propertyFile);
					try {
						pro.store(out, "修改预警值");
						JOptionPane.showMessageDialog(KcAlertDialog.this, "确定");
						getContentPane().getParent().validate();
					} catch (IOException e1) {
						// TODO Auto-generated catch block
						e1.printStackTrace();
					}
				} catch (FileNotFoundException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				} finally {
					try {
						out.close();
					} catch (IOException e1) {
						// TODO Auto-generated catch block
						e1.printStackTrace();
					}

				}
			}
		});

		jButton2.setCursor(new Cursor(Cursor.HAND_CURSOR));
		jButton2.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub
				KcAlertDialog.this.dispose();
			}
		});

		jLabel1.setBounds(30, 30, 60, 30);
		jLabel6.setBounds(100, 70, 100, 30);
		jLabel7.setBounds(100, 110, 100, 30);
		jLabel9.setBounds(360, 70, 60, 30);
		jLabel10.setBounds(360, 110, 60, 30);
		jLabel13.setBounds(460, 70, 60, 30);
		jLabel14.setBounds(460, 110, 60, 30);
		jLabel15.setBounds(360, 190, 60, 30);
		jLabel16.setBounds(100, 30, 100, 30);
		jTextField1.setEditable(false);
		jLabel11.setBounds(100, 150, 100, 30);
		jTextField1.setBounds(460, 190, 60, 30);
		jTextField2.setBounds(130, 190, 60, 30);
		jLabel8.setBounds(360, 30, 60, 30);
		jLabel12.setBounds(460, 30, 60, 30);
		jLabel2.setBounds(30, 70, 60, 30);
		jLabel3.setBounds(30, 110, 60, 30);
		jLabel4.setBounds(30, 150, 60, 30);
		jLabel5.setBounds(30, 190, 100, 30);
		jButton1.setBounds(150, 260, 80, 30);
		jButton2.setBounds(350, 260, 80, 30);

		this.add(jLabel11);
		this.add(jTextField2);
		this.add(jTextField1);
		this.add(jLabel6);
		this.add(jLabel7);
		this.add(jLabel8);
		this.add(jLabel9);
		this.add(jLabel10);
		this.add(jLabel12);
		this.add(jLabel13);
		this.add(jLabel14);
		this.add(jLabel15);
		this.add(jLabel16);
		this.add(jLabel2);
		this.add(jLabel3);
		this.add(jLabel4);
		this.add(jLabel5);
		this.add(jLabel8);
		this.add(jLabel1);
		this.add(jButton1);
		this.add(jButton2);

		pack();
	}// </editor-fold>
		// GEN-END:initComponents

	/**
	 * @param args
	 *            the command line arguments
	 */

	public String getAlertValue() {
		return jTextField2.getText();
	}

	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				KcAlertDialog dialog = new KcAlertDialog(
						new javax.swing.JFrame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
			}
		});
	}

	// GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel15;
	private javax.swing.JLabel jLabel16;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField1;

	// End of variables declaration//GEN-END:variables
}