/*
 * PriceChangeDialog.java
 *
 * Created on __DATE__, __TIME__
 */

package com.sxt.view.kcgl_view;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.util.Vector;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.event.AncestorEvent;
import javax.swing.event.AncestorListener;

import com.sxt.dao.factory.DaoFactory;


/**
 * 
 * @author __USER__
 */
public class PriceUpdate extends javax.swing.JDialog implements
		ItemListener {
	private Vector<Vector> data;
	private Vector<String> name;

	/** Creates new form PriceChangeDialog */
	public PriceUpdate(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		setPreferredSize(new Dimension(600, 350));
		initComponents();
		setLocationRelativeTo(null);
		setVisible(true);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {
		this.setLayout(null);
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jComboBox1 = new javax.swing.JComboBox();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jTextField2 = new javax.swing.JTextField();
		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();
		jLabel11 = new javax.swing.JLabel();
		jLabel12 = new javax.swing.JLabel();
		jLabel13 = new javax.swing.JLabel();
		jLabel14 = new javax.swing.JLabel();
		jTextField3 = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		jLabel1.setText("商品名称");

		jLabel2.setText("产地");

		jLabel3.setText("包装");

		jLabel4.setText("单价");

		jLabel5.setText("库存金额");

		jComboBox1.setModel(new DefaultComboBoxModel());

		jLabel6.setText("jLabel6");

		jLabel7.setText("jLabel7");

		jTextField1.setText("jTextField1");

		jTextField2.setText("jTextField2");

		jLabel8.setText("规格");

		jLabel9.setText("简称");

		jLabel10.setText("单位");

		jLabel11.setText("数量");

		jLabel12.setText("jLabel12");

		jLabel13.setText("无");

		jLabel14.setText("jLabel14");

		jTextField3.setText("jTextField3");

		jButton1.setText("确定");
		jButton1.setCursor(new Cursor(Cursor.HAND_CURSOR));

		jButton1.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub
				//将调整改变过的价格保存到数据库当中
				String price = jTextField1.getText();
				String goodsName = jComboBox1.getSelectedItem().toString();
				System.out.println(price + goodsName);
				int a = DaoFactory.getKcDao().goodsPriceUpdate(price,
						goodsName);
				if (a > 0) {
					JOptionPane.showMessageDialog(PriceUpdate.this,
							"调整成功");
					PriceUpdate.this.dispose();
				}
			}
		});

		jButton2.setText("关闭");
		jButton2.setCursor(new Cursor(Cursor.HAND_CURSOR));
		jButton2.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub
				PriceUpdate.this.dispose();
			}
		});
		jLabel1.setBounds(30, 30, 60, 30);
		jLabel6.setBounds(100, 70, 150, 30);
		jLabel7.setBounds(100, 110, 60, 30);
		jLabel9.setBounds(360, 70, 60, 30);
		jLabel10.setBounds(360, 110, 60, 30);
		jLabel11.setBounds(360, 150, 60, 30);
		jLabel13.setBounds(430, 70, 60, 30);
		jLabel14.setBounds(430, 110, 60, 30);
		jTextField3.setBounds(430, 150, 60, 30);
		jTextField3.setEditable(false);
		jTextField1.setBounds(100, 150, 60, 30);
		jTextField2.setBounds(100, 190, 60, 30);
		jTextField2.setEditable(false);
		jComboBox1.setBounds(100, 35, 150, 25);
		jLabel8.setBounds(360, 30, 60, 30);
		jLabel12.setBounds(430, 30, 60, 30);
		jLabel2.setBounds(30, 70, 60, 30);
		jLabel3.setBounds(30, 110, 60, 30);
		jLabel4.setBounds(30, 150, 60, 30);
		jLabel5.setBounds(30, 190, 60, 30);
		jButton1.setBounds(150, 260, 80, 30);
		jButton2.setBounds(350, 260, 80, 30);

		name = new Vector<String>();
		data = DaoFactory.getKcDao().goodsInquiry();
		for (int i = 0; i < data.size(); i++) {
			String dbname = data.get(i).get(1).toString();
			name.add(dbname);
		}
		DefaultComboBoxModel dcbm = new DefaultComboBoxModel(name);
		jComboBox1.setModel(dcbm);

		// 下拉框加载时给此会话填充数据
		jComboBox1.addAncestorListener(new AncestorListener() {
			@Override
			public void ancestorRemoved(AncestorEvent event) {
			}

			public void ancestorMoved(AncestorEvent event) {
			}

			public void ancestorAdded(AncestorEvent event) {
				setLableText(data, 0);
			}
		});

		this.add(jTextField1);
		this.add(jTextField2);
		this.add(jTextField3);
		this.add(jLabel6);
		this.add(jLabel7);
		this.add(jLabel8);
		this.add(jLabel9);
		this.add(jLabel10);
		this.add(jLabel11);
		this.add(jLabel12);
		this.add(jLabel13);
		this.add(jLabel14);
		this.add(jLabel2);
		this.add(jLabel3);
		this.add(jLabel4);
		this.add(jLabel5);
		this.add(jLabel8);
		this.add(jComboBox1);
		this.add(jLabel1);
		this.add(jButton1);
		this.add(jButton2);
		jComboBox1.addItemListener(this);

		pack();
	}// </editor-fold>
		// GEN-END:initComponents

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				PriceUpdate dialog = new PriceUpdate(
						new javax.swing.JFrame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}
    
	public void setLableText(Vector<Vector> data, int i) {

		jLabel6.setText(data.get(i).get(2).toString());

		jLabel7.setText(data.get(i).get(5).toString());

		jTextField1.setText(data.get(i).get(6).toString());

		int price = Integer.parseInt(data.get(i).get(6).toString());
		int num = Integer.parseInt(data.get(i).get(7).toString());
		int total = price * num;
		jTextField2.setText(Integer.toString(total));

		jLabel12.setText(data.get(i).get(4).toString());

		jLabel14.setText(data.get(i).get(3).toString());

		jTextField3.setText(data.get(i).get(7).toString());

	}

	// GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JComboBox jComboBox1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField3;

	// End of variables declaration//GEN-END:variables

	// 下拉框选择时填充会话内容的事件
	@Override
	public void itemStateChanged(ItemEvent e) {
		// TODO Auto-generated method stub
		if (e.getStateChange() == ItemEvent.SELECTED) {
			// TODO Auto-generated method stub
			int num = name.size();
			for (int i = 0; i < num; i++) {
				if (e.getItem().toString().equals(name.get(i)))
					setLableText(data, i);
			}

		}

	}

}